name: floating_bubbles
description: A Flutter Package for adding Floating bubbles on the Foreground to any Flutter widget.
version: 3.1.0
homepage: https://github.com/Poujhit/floating_bubbles
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  simple_animations: ^5.0.2
  #Sound
  audioplayers: ^5.1.0
  #Path_provider
  path_provider: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    -  packages/floating_bubbles/assets/bubble.mp3
