name: floating_bubbles
description: A Flutter Package for adding Floating bubbles on the Foreground to any Flutter widget.
version: 3.0.0
homepage: https://github.com/Poujhit/floating_bubbles
environment:
  sdk: ">=2.17.6 <3.7.0"
  flutter: '>=2.17.6'

dependencies:
  simple_animations: ^4.1.0
  #Sound
  audioplayers: ^3.0.1
  #Path_provider
  path_provider: ^2.0.12
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    -  packages/floating_bubbles/assets/bubble.mp3
