name: floating_bubbles
description: A Flutter Package for adding Floating bubbles on the Foreground to any Flutter widget.
version: 2.1.2
homepage: https://github.com/Poujhit/floating_bubbles
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  simple_animations: ^4.0.2
  #Sound
  audioplayers: ^0.20.1
  #Path_provider
  path_provider: ^2.0.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    -  packages/floating_bubbles/assets/bubble.mp3
